spring:
    datasource:
        url: jdbc:mysql://localhost:3306/challenge-backend
        username: root
        password: 12345
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
                strategy: org.hibernate.cfg.ImprovedNaming.Strategy
        properties:
            dialect: org.hibernate.dialect.MySQL5Dialect
    sendgrid:
           api-key: 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

